Add log level
dappnode/monitor-service pull request #80
Opened 2023-06-13 18:37 UTC by dsimog01

Implemented log levels: `DEBUG, INFO. WARN, ERROR, FATAL`

2023-06-13 19:32 UTC, pablomendezroyo requested changes

2023-06-13 19:32 UTC, pablomendezroyo commented on register/Dockerfile
> -CMD ["./register"]
I would set the env through the compose file

2023-06-13 20:37 UTC, dsimog01 commented on register/Dockerfile
> -CMD ["./register"]
Done!

2023-06-14 06:29 UTC, pablomendezroyo approved these changes

2023-06-14 06:30 UTC, merged